CREATE TABLE Patients_Information(
	ID INT PRIMARY KEY,
	Name NVARCHAR NOT NULL
)

CREATE TABLE Disease_Information(
	ID INT PRIMARY KEY,
	Name NVARCHAR NOT NULL
)

CREATE TABLE NCD(
	ID INT PRIMARY KEY,
	Name NVARCHAR NOT NULL
)

CREATE TABLE Allergies(
	ID INT PRIMARY KEY,
	Name NVARCHAR NOT NULL
)

CREATE TABLE NCD_Details(
	ID INT PRIMARY KEY,
	PatientID INT NOT NULL,
	NCDID INT NOT NULL,

	CONSTRAINT FK_NCD_Details_Patients_Information FOREIGN KEY (PatientID) REFERENCES Patients_Information (ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	CONSTRAINT FK_NCD_Details_NCD FOREIGN KEY (NCDID) REFERENCES NCD (ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)

CREATE TABLE Allergies_Details(
	ID INT PRIMARY KEY, 
	PatientID INT NOT NULL,
	AllergiesID INT NOT NULL,

	CONSTRAINT FK_Allergies_Details_Patients_Information FOREIGN KEY (PatientID) REFERENCES Patients_Information (ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	CONSTRAINT FK_Allergies_Details_Allergies FOREIGN KEY (AllergiesID) REFERENCES Allergies (ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)